---
- name: Verify_All
  hosts: all
  gather_facts: true
  tasks:
    - name: "Set variables"
      set_fact:
        sites: ['https://google.com', 'https://github.com']

    - name: Test that my module works
      check_url:
        url: "{{site}}"
      with_items: "{{sites}}"
      loop_control:
        loop_var: site
      register: result

    - debug: var=result
